name: Zip Test
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: pwd
    - uses: actions/checkout@master
    - name: Prepare release
      shell: bash
      run: |
        cd ..
        mkdir Test
        touch Test/Test.bin
        chmod +x Test/Test.bin
    - name: Archive release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: zip
        directory: ..
        filename: Test.zip
        path: Test
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: Test
        path: /home/runner/work/jv98289v890j/Test.zip
  build-windows:
    runs-on: windows-latest
    steps:
    - shell: bash
      run: pwd
    - shell: pwsh
      run: Get-Location
    - uses: actions/checkout@master
    - name: Prepare release
      shell: bash
      run: |
        cd ..
        mkdir Test
        touch Test/Test.bin
    - name: Archive release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: zip
        directory: ..
        filename: Test.zip
        path: Test
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: Test-Windows
        path: D:\a\jv98289v890j\Test.zip
